version: 0.2

phases:
  install:
    commands:
      - echo Installing Dependencies
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t hshar/webapp .
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - '**/*'

